use async_trait::async_trait;
use std::env;
use titanium_model::EmbedBuilder;
use titanium_rs::prelude::*;

// Example: Embeds Bot
#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();
    let token = env::var("DISCORD_TOKEN").expect("Expected DISCORD_TOKEN");

    let client = Client::builder(token)
        .intents(Intents::GUILDS | Intents::GUILD_MESSAGES)
        .event_handler(EmbedHandler)
        .build()
        .await
        .expect("Failed to build client");

    if let Err(why) = client.start().await {
        eprintln!("Client error: {:?}", why);
    }
}

struct EmbedHandler;

#[async_trait]
impl EventHandler for EmbedHandler {
    async fn ready(&self, _ctx: Context, ready: ReadyEventData<'_>) {
        println!("Logged in as {}", ready.user.username);
        println!("Send !embed to see a rich embed.");
    }

    async fn message_create(&self, ctx: Context, msg: Message<'_>) {
        if msg.content == "!embed" {
            let embed = EmbedBuilder::new()
                .title("Titanium-rs Embed Example")
                .description("This is a rich embed generated by **Titanium-rs**.")
                .color(0x00AABB) // Teal
                .field("Field 1", "Some inline value", true)
                .field("Field 2", "Another inline value", true)
                .footer("Powered by Titanium-rs", None::<String>)
                .timestamp(titanium_model::string::TitanString::from(
                    "2025-01-01T12:00:00Z",
                ));

            let response = titanium_model::builder::MessageBuilder::new()
                .content("Here is your requested embed:")
                .embed(embed)
                .build();

            if let Err(e) = ctx.http.create_message(msg.channel_id, &response).await {
                eprintln!("Error sending message: {:?}", e);
            }
        }
    }
}
